# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool: local-machine

steps:
- checkout: self

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'echo "##vso[task.setvariable variable=JAVA_HOME]/Users/falmeida/Library/Java/JavaVirtualMachines/corretto-17.0.10/Contents/Home" && echo "##vso[task.setvariable variable=M2_HOME]/usr/local/Cellar/maven/3.9.6/libexec"'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'echo "##vso[task.setvariable variable=PATH]$(M2_HOME)/bin:$(PATH)"'
- script: ls -l $(Pipeline.Workspace)
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'package'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11' 
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
    
