# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool: local-machine

steps:
- checkout: self
- script: pwd
- script: ls -l $(Build.Repository.LocalPath)
- task: JavaToolInstaller@0
  inputs:
      versionSpec: '11' # string. Required. JDK version. Default: 8.
      jdkArchitectureOption: 'x64' #| 'x86'. Required. JDK architecture.
      jdkSourceOption: LocalDirectory
      jdkFile: "/Users/falmeida/env-dev/open-jdk-binaries/JAVA_HOME_11_X64_microsoft-jdk-11.0.22-macos-x64_tar.gz/jdk-11.0.22+7/Contents/Home/homefolder.zip"
- task: Maven@3
  inputs:
    mavenPomFile: '$(Build.Repository.LocalPath)/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
